#!/bin/bash -e

swapfile="/swapfile"

sudo fallocate -l 4G ${swapfile}
sudo chmod 600 ${swapfile}
sudo mkswap ${swapfile}
sudo swapon ${swapfile}
printf '/swapfile   none    swap    sw    0   0\n' >> /etc/fstab
